import './globals.css'
import { Inter } from 'next/font/google'
import Provider from '@/components/Provider'
import Nav from '@/components/Nav'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Promtpedia',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-blue-200  to-pink-300 h-screen">
      <Provider>
      <Nav/>
      {children}
      </Provider>
      </body>
    </html>
  )
}
